### ISSUE TITLE
Can't find repo path in config

### ISSUE THREAD

**Issue by white-gecko** [AKSW/QuitStore#112]
#111 introduced a bug, which makes quit store not startable (configmode graphfiles) with the following message:

```
Traceback (most recent call last):
  File "/usr/local/bin/quit", line 165, in <module>
    objects = initialize(args)
  File "/usr/local/bin/quit", line 81, in initialize
    config.initgraphconfig()
  File "/usr/src/app/quit/conf.py", line 114, in initgraphconfig
    self.__initgraphconfig()
  File "/usr/src/app/quit/conf.py", line 128, in __initgraphconfig
    self.__initgraphsfromdir(self.getRepoPath())
  File "/usr/src/app/quit/conf.py", line 135, in __initgraphsfromdir
    graphs = self.getgraphsfromdir(repodir)
  File "/usr/src/app/quit/conf.py", line 463, in getgraphsfromdir
    for dirpath, dirs, files in walk(path):
  File "/usr/local/lib/python3.6/os.py", line 335, in walk
    top = fspath(top)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by white-gecko** [comment]
This configuration works:

```
@base <http://my.quit.conf/> .
@prefix quit: <http://quit.aksw.org/vocab/> .

<store> a quit:QuitStore ;
    quit:pathOfGitRepo "/data/" . # Set the path to the repository that contains the files .
```
