### ISSUE TITLE
Error with FROM in query

### ISSUE THREAD

**Issue by white-gecko** [AKSW/QuitStore#116]
```
[2018-02-13 15:42:13,396] ERROR in app: Exception on /sparql [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rdflib/plugins/sparql/sparql.py", line 266, in _load
    return graph.load(source, format='nt', **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rdflib/graph.py", line 1050, in load
    self.parse(source, publicID, format)
  File "/usr/local/lib/python3.6/site-packages/rdflib/graph.py", line 1488, in parse
    file=file, data=data, format=format)
  File "/usr/local/lib/python3.6/site-packages/rdflib/parser.py", line 186, in create_input_source
    input_source = URLInputSource(absolute_location, format)
  File "/usr/local/lib/python3.6/site-packages/rdflib/parser.py", line 106, in __init__
    file = urlopen(req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./quit/web/modules/endpoint.py", line 110, in sparql
    res = graph.query(parsedQuery)
  File "./quit/core.py", line 84, in query
    return self.store.query(querystring)
  File "/usr/local/lib/python3.6/site-packages/rdflib/graph.py", line 1089, in query
    query_object, initBindings, initNs, **kwargs))
  File "./quit/tools/processor.py", line 40, in query
    return evalQuery(self.graph, query, initBindings, base)
  File "./quit/tools/evaluate.py", line 481, in evalQuery
    ctx.load(d.default, default=True)
  File "/usr/local/lib/python3.6/site-packages/rdflib/plugins/sparql/sparql.py", line 280, in load
    _load(self.graph, source)
  File "/usr/local/lib/python3.6/site-packages/rdflib/plugins/sparql/sparql.py", line 270, in _load
    source))
Exception: Could not load http://example.org/graph/ as either RDF/XML, N3 or NTriples
[pid: 7|app: 0|req: 1267/1267] 172.18.0.1 () {30 vars in 408 bytes} [Tue Feb 13 15:41:12 2018] POST /quitstore/sparql => generated 291 bytes in 61173 msecs (HTTP/1.1 500) 3 headers in 116 bytes (2 switches on core 0)

```

**Comment by white-gecko** [comment]
I've reported this issue upstream: https://github.com/RDFLib/rdflib/issues/810
