### ISSUE TITLE
Parsing ntriples failes with underscore in blankid

### ISSUE THREAD

**Issue by rmeissn** [AKSW/QuitStore#217]
Using QuitStore from docker hub, tag 2018-12-14.

I've started a new quitstore container from scratch, using a docker volume to store its data. I've inserted via sparql some data (from git log):
```sparql
INSERT DATA {
      GRAPH <http://localhost:3000/data> {
        <http://localhost/item/1> <http://purl.org/dc/terms/title> "Test Question".
        <http://localhost/item/1> <http://tech4comp/eal/context> "This is a test setting".
        <http://localhost/item/1> <http://tech4comp/eal/difficulty> "9.6E0"^^<http://www.w3.org/2001/XMLSchema#double>.
        <http://localhost/item/1> <http://tech4comp/eal/hasAnswerText> _:b0_b0.
        <http://localhost/item/1> <http://tech4comp/eal/hasContributor> "http://whatever.de".
        <http://localhost/item/1> <http://tech4comp/eal/hasCorrectAnswer> 0 .
        <http://localhost/item/1> <http://tech4comp/eal/hasCorrectAnswer> 1 .
        <http://localhost/item/1> <http://tech4comp/eal/hasKnowledgeDimension> "http://whatever.de".
        <http://localhost/item/1> <http://tech4comp/eal/hasLearningOutcome> "http://whatever.de".
        <http://localhost/item/1> <http://tech4comp/eal/hasPerformanceLevel> "http://whatever.de".
        <http://localhost/item/1> <http://tech4comp/eal/hasProject> "http://whatever.de".
        <http://localhost/item/1> <http://tech4comp/eal/points> 5 .
        <http://localhost/item/1> <http://tech4comp/eal/task> "Solve the task!".
        <http://localhost/item/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://tech4comp/eal/item>.
        _:b1_b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "42".
        _:b1_b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1_b1.
        _:b1_b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "43".
        _:b1_b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1_b2.
        _:b1_b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "41".
        _:b1_b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>.
      }
    }
``` 

Querying the data worked fine, as long as the quit store has not been restarted. As of the next reboot of my host system (container has auto restart policy), it's not possible to query the sparql endpoint anymore.  The gui tells me "Bad Request (400), no branch or reference given". Quitstore logs show:

```log
2018-12-18 09:13:09,206 - quit.modules.endpoint - DEBUG - Request method: POST
2018-12-18 09:13:09,259 - quit.conf.QuitConfiguration - DEBUG - Initializing configuration object.
2018-12-18 09:13:09,288 - quit.modules.endpoint - ERROR - Invalid line: '_b0 .'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 154, in parse
    self.parseline()
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 204, in parseline
    self.eat(r_tail)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 218, in eat
    raise ParseError("Failed to eat %s at %s" % (pattern.pattern, self.line))
rdflib.plugins.parsers.ntriples.ParseError: Failed to eat [ \t]*\.[ \t]*(#.*)? at _b0 .
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./quit/web/modules/endpoint.py", line 93, in sparql
    graph, commitid = quit.instance(branch_or_ref)
  File "./quit/core.py", line 192, in instance
    (f, context) = self.getFileReferenceAndContext(blob, commit)
  File "./quit/core.py", line 411, in getFileReferenceAndContext
    graph.parse(data=content, format='nt')
  File "/usr/local/lib/python3.7/site-packages/rdflib/graph.py", line 1030, in parse
    parser.parse(source, self, **args)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/nt.py", line 26, in parse
    parser.parse(f)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 156, in parse
    raise ParseError("Invalid line: %r" % self.line)
rdflib.plugins.parsers.ntriples.ParseError: Invalid line: '_b0 .'
[pid: 8|app: 0|req: 22/22] 172.17.0.1 () {46 vars in 1138 bytes} [Tue Dec 18 09:13:09 2018] POST /sparql => generated 29 bytes in 91 msecs (HTTP/1.1 400) 3 headers in 120 bytes (1 switches on core 0)
```

The data inside the .nt files in the docker volume looks perfectly fine though:
```turtle
<http://localhost/item/1> <http://purl.org/dc/terms/title> "Test Question" .
<http://localhost/item/1> <http://tech4comp/eal/context> "This is a test setting" .
<http://localhost/item/1> <http://tech4comp/eal/difficulty> "9.6E0"^^<http://www.w3.org/2001/XMLSchema#double> .
<http://localhost/item/1> <http://tech4comp/eal/hasAnswerText> _:b1_b0 .
<http://localhost/item/1> <http://tech4comp/eal/hasContributor> "http://whatever.de" .
<http://localhost/item/1> <http://tech4comp/eal/hasCorrectAnswer> "0"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://localhost/item/1> <http://tech4comp/eal/hasCorrectAnswer> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://localhost/item/1> <http://tech4comp/eal/hasKnowledgeDimension> "http://whatever.de" .
<http://localhost/item/1> <http://tech4comp/eal/hasLearningOutcome> "http://whatever.de" .
<http://localhost/item/1> <http://tech4comp/eal/hasPerformanceLevel> "http://whatever.de" .
<http://localhost/item/1> <http://tech4comp/eal/hasProject> "http://whatever.de" .
<http://localhost/item/1> <http://tech4comp/eal/points> "5"^^<http://www.w3.org/2001/XMLSchema#integer> .
<http://localhost/item/1> <http://tech4comp/eal/task> "Solve the task!" .
<http://localhost/item/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://tech4comp/eal/item> .
_:b1_b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "42" .
_:b1_b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1_b1 .
_:b1_b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "43" .
_:b1_b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1_b2 .
_:b1_b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "41" .
_:b1_b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
...
```

**Comment by white-gecko** [comment]
This is blocked by https://github.com/RDFLib/rdflib/issues/888

**Comment by white-gecko** [comment]
A workaround is to not use underscore (`_`) in blank labels.

**Comment by rmeissn** [comment]
Unfortunately there is no easy way to tell the jsonld library to not use underscores as part of blank node labels. Is it possible to add a workaround hook script to the quit-store that processes blank nodes before they are committed? E.g. to transform `_:b1_b2` to `_:b1b2`. Quit uses a working repository (not a bare one), right?

**Comment by white-gecko** [comment]
I think the pre-commit hooks are not triggered by the pygit2 library. So this will not easily work. Fixing it in rdflib is the best option.

**Comment by white-gecko** [comment]
I've tagged a new version, which should include the updated rdflib fork on https://github.com/white-gecko/rdflib/tree/merge/forQuit.
