### ISSUE TITLE
configmode remoteconfig can't be selected

### ISSUE THREAD

**Issue by white-gecko** [AKSW/QuitStore#23]
starting quit with `--configmode remoteconfig` fails with error:

    quit: error: argument -cm/--configmode: invalid choice: 'remoteconfig' (choose from 'graphfiles', 'localconfig', 'repoconfig')

but it is mentioned like this here:
- https://github.com/AKSW/QuitStore/blob/ddb3d284954212715a30322cf17e05bd05d022a5/quit/conf.py#L93
- https://github.com/AKSW/QuitStore/blob/ddb3d284954212715a30322cf17e05bd05d022a5/tests/test_conf.py#L94

calling quit with `--configmode repoconfig` fails with:

```
Traceback (most recent call last):
  File "/usr/local/bin/quit", line 645, in <module>
    objects = initialize(args)
  File "/usr/local/bin/quit", line 224, in initialize
    config.initgraphconfig()
  File "/usr/src/app/quit/conf.py", line 84, in initgraphconfig
    self.__initgraphconfig()
  File "/usr/src/app/quit/conf.py", line 99, in __initgraphconfig
    raise InvalidConfigurationError('This mode is not supported.', self.configmode)
AttributeError: 'QuitConfiguration' object has no attribute 'configmode'
```

**Comment by white-gecko** [comment]
Setting ` quit:configMode "remoteconfig"` in the store's `config.ttl` doesn't fail.
