### ISSUE TITLE
pyinstaller release 0.24.1 does not start

### ISSUE THREAD

**Issue by white-gecko** [AKSW/QuitStore#255]
pyinstaller release 0.24.1 for linux does throw an error and does not start:

```
Traceback (most recent call last):
  File "quit/run.py", line 8, in <module>
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "quit/application.py", line 4, in <module>
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "quit/conf.py", line 4, in <module>
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/pygit2/__init__.py", line 33, in <module>
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/pygit2/blame.py", line 27, in <module>
  File "/root/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "site-packages/pygit2/ffi.py", line 27, in <module>
ModuleNotFoundError: No module named '_cffi_backend'
[4076] Failed to execute script run

```

**Comment by white-gecko** [comment]
Solution is to add _cffi_backend to hiddenimports. (https://github.com/pyinstaller/pyinstaller/issues/1684#issuecomment-449607479)

**Comment by 6zmj** [comment]
255, 255, 0.24
