### ISSUE TITLE
binary release doesn't work on manjaro

### ISSUE THREAD

**Issue by white-gecko** [AKSW/QuitStore#291]
```
Traceback (most recent call last):
  File "quit/run.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "quit/application.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "quit/conf.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pygit2/__init__.py", line 230, in <module>
  File "pygit2/settings.py", line 55, in __init__
  File "pygit2/settings.py", line 61, in _initialize_tls_certificate_locations
  File "pygit2/settings.py", line 191, in set_ssl_cert_locations
_pygit2.GitError: OpenSSL error: failed to load certificates: error:00000000:lib(0):func(0):reason(0)
[149344] Failed to execute script 'run' due to unhandled exception!
```

**Comment by white-gecko** [comment]
Does work within a ubuntu docker container either.

**Comment by MartyStache** [comment]
@white-gecko 

I found this…Manjaro related. Not sure if it’ll help: https://github.com/iterative/dvc/issues/7429

**Comment by MartyLake** [comment]
For the record, this it still an issue today.
Is this package used by anyone?

**Comment by white-gecko** [comment]
I have tried to get it working with pyinstaller again but I did not figure it out. Currently its best to use the docker image.

**Comment by white-gecko** [comment]
You can also get it into your path using `pipx`

```
$ pipx install git+https://github.com/AKSW/QuitStore.git
  installed package quit 0.25.4, installed using Python 3.12.1
  These apps are now globally available
    - quitstore
done! ✨ 🌟 ✨
$ quitstore --help
```

**Comment by MartyLake** [comment]
Installing with `pip3` directly from git+https... also works! Now, I need to figure out how it works.
