### ISSUE TITLE
Error if an empty graph was committed

### ISSUE THREAD

**Issue by white-gecko** [AKSW/QuitStore#76]
If an empty graph was committed we sometimes receive the following error:

```
Traceback (most recent call last):
  File "/usr/src/app/quit/web/modules/endpoint.py", line 91, in sparql
    branch_or_ref, ref, query=q
  File "/usr/src/app/quit/core.py", line 437, in commit
    self.syncSingle(commit, delta)
  File "/usr/src/app/quit/core.py", line 156, in syncSingle
    self.changeset(commit, delta)
  File "/usr/src/app/quit/core.py", line 244, in changeset
    i1 = self.instance(commit.id, True)
  File "/usr/src/app/quit/core.py", line 207, in instance
    f, contexts = self._blobs.get(oid)
TypeError: 'NoneType' object is not iterable 
```

**Comment by white-gecko** [comment]
Duplicate of #78
